version: "3.2"
services:
  node:
    build: './node/'
    command: npm run dev
    networks:
      - backend
    volumes:
      - .:/home/node/app/
      - /home/node/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://todoapp@postgres/todos
  postgres:
    image: postgres:latest
    networks:
      - backend
    environment:
      - POSTGRES_DB=todos
      - POSTGRES_USER=todoapp
networks:
  frontend:
  backend: