version: "3.2"
services:
  #angular-client:
  #express-server:
  node-backend:
    build: './node-backend/'
    networks:
      - backend
    #volumes:
    #  - ./node-backend/src/:/home/node/app/
    ports:
      - "5060:5060"
    depends_on:
      - postgres
    environment:
      NODE_ENV: ${ENVIRONMENT}
      POSTGRES_URL: postgres://${POSTGRES_USER}@${POSTGRES_HOST}/{POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      BOT_PREFIX: ${BOT_PREFIX}
      BOT_TOKEN: ${BOT_TOKEN}
  postgres:
    image: postgres:latest
    restart: always
    networks:
      - backend
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - $HOME/postgresql/data:/var/lib/postgresql/data
networks:
  frontend:
  backend: